version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
              - ./docker_volume/db:/data/db
        networks:
            - network_1

    service-a:
        container_name: service_a
        hostname: service_a
        build: 
          context: ./service-a
        depends_on:
            - mongo
        volumes:
            - "./docker_volume/service-a:/src/app"
        ports:
          - 3000:3000
        networks:
            - network_1
      
    service-b:
        container_name: service_b
        hostname: service_b
        build: 
          context: ./service-b
        depends_on:
            - mongo
        volumes:
            - "./docker_volume/service-b:/src/app"
        ports:
          - 3001:3000
        networks:
            - network_1

    nginx:
        container_name: nginx
        hostname: nginx
        build: 
          context: ./nginx
        depends_on:
            - service-a
            - service-b
        ports:
            - 80:80
        networks:
            - network_1

networks:
    network_1:
      external: true